"""
Utility script for moving files to a specified directory.

"""

import os
import shutil

category = "test"
TEXT_FILE = f"{category}.txt"
SOURCE_FOLDER = "masks"
OUTPUT_FOLDER = f"masks\{category}"


def move_images_to_output(
    text_file,
    output_folder,
    source_folder,
    possible_extensions=[".jpg", ".jpeg", "_m.png"],
):
    """
    Moves images listed in a text file to a specified output folder.
    Attempts to find images with multiple possible extensions.

    Parameters:
    - text_file: Path to the text file containing image names.
    - output_folder: Path to the output folder where images should be moved.
    - source_folder: Path to the source folder containing the images.
    - possible_extensions: List of possible file extensions to try for each image name.

    Generated by CHATGPT
    """
    with open(text_file, "r") as file:
        for base_image_name in file:
            base_image_name = base_image_name.strip()
            image_found = False

            for extension in possible_extensions:
                image_name = base_image_name + extension
                source_path = os.path.join(source_folder, image_name)
                if os.path.exists(source_path):
                    destination_path = os.path.join(output_folder, image_name)
                    shutil.move(source_path, destination_path)
                    image_found = True
                    print(f"Moved: {source_path} to {destination_path}")
                    break  # Found the correct extension, no need to check further

            if not image_found:
                print(
                    f"Image not found with any of the provided extensions: {base_image_name}"
                )


move_images_to_output(
    text_file=TEXT_FILE, source_folder=SOURCE_FOLDER, output_folder=OUTPUT_FOLDER
)
